---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '9035'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.2
    ports:
    - 9035:9035
    - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'

  postgres:
    image: postgres:16-alpine
    container_name: rag_postgress
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - rag_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped


  test-db:
    image: postgres:16-alpine
    container_name: rag_postgres_test
    environment:
      POSTGRES_DB: ragtest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - rag_postgres_data_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  rag_postgres_data:
  rag_postgres_data_test:
...
